[project]
name = "pfe-django"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "mohamed el houdaigui", email = "mohamedelhoudaigui27@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "django>=6.1",
    "django-htmx>=1.29.0",
    "faker>=40.37.0",
]

[tool.uv]
package = false
