# Generated by Django 5.2.15 on 2026-06-29 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CivilServant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CIN', models.CharField(max_length=20, unique=True)),
                ('PPR', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_de_naissance', models.DateField()),
                ('lieu_de_naissance', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('man', 'Homme'), ('woman', 'Femme')], max_length=10)),
                ('situation_familiale', models.CharField(choices=[('single', 'Célibataire'), ('married', 'Marié(e)'), ('divorced', 'Divorcé(e)')], max_length=20)),
                ('n_enfants', models.PositiveIntegerField(default=0)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('category', models.CharField(choices=[('technicien', 'Techniciens')], max_length=100)),
                ('grade', models.CharField(choices=[('1G', '1G'), ('2G', '2G'), ('3G', '3G'), ('4G', '4G')], max_length=10)),
                ('echelon', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13')])),
                ('indice', models.PositiveSmallIntegerField(editable=False)),
                ('mutuelle', models.CharField(choices=[('CNOPS', 'CNOPS')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fonct', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='JobDetail', to='core.civilservant')),
            ],
        ),
    ]
