# Generated by Django 5.2.15 on 2026-07-22 12:11

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CivilServant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CIN', models.CharField(max_length=20, unique=True)),
                ('PPR', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_de_naissance', models.DateField()),
                ('lieu_de_naissance', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('man', 'man'), ('woman', 'woman')], max_length=10)),
                ('situation_familiale', models.CharField(choices=[('single', 'single'), ('married', 'married'), ('divorced', 'married')], max_length=20)),
                ('n_enfants', models.PositiveIntegerField(default=0)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='civil_servant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('categorie', models.CharField(choices=[('technicien', 'technicien')], max_length=100)),
                ('grade', models.CharField(choices=[('1G', '1G'), ('2G', '2G'), ('3G', '3G'), ('4G', '4G')], max_length=10)),
                ('echelle', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')])),
                ('echelon', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13')])),
                ('indice', models.PositiveSmallIntegerField(editable=False)),
                ('mutuelle', models.CharField(choices=[('CNOPS', 'CNOPS')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('civil_servant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='JobDetail', to='core.civilservant')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('indemnities', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('tsp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('family_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('annual_gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cmr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sm', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ccd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('income_reduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taxable_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('income_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('civil_servant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='SalaryDetail', to='core.civilservant')),
            ],
        ),
    ]
