# Generated by Django 6.1 on 2026-08-26 13:52

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('label', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CivilServant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CIN', models.CharField(max_length=20, unique=True)),
                ('PPR', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_de_naissance', models.DateField()),
                ('lieu_de_naissance', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('man', 'man'), ('woman', 'woman')], max_length=10)),
                ('situation_familiale', models.CharField(choices=[('single', 'single'), ('married', 'married'), ('divorced', 'married')], max_length=20)),
                ('n_enfants', models.PositiveIntegerField(default=0)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='civil_servant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.categorie')),
            ],
            options={
                'unique_together': {('categorie', 'code')},
            },
        ),
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('categorie', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=10)),
                ('echelle', models.CharField(help_text='Associated with grade, e.g. tech 4th grade = échelle 9', max_length=10)),
                ('echelon', models.PositiveSmallIntegerField(help_text="1–11, includes 'exceptionnelle'")),
                ('indice', models.PositiveSmallIntegerField(help_text="Échelon's salary-calc representation")),
                ('mutuelle', models.CharField(choices=[('CNOPS', 'CNOPS')], max_length=50)),
                ('position', models.CharField(choices=[('en_activite', 'En activité'), ('abandon_de_poste', 'Abandon de poste'), ('conge_de_maladie', 'Congé de maladie'), ('decharge_syndicale', 'Décharge syndicale'), ('demission', 'Démission'), ('detachement', 'Détachement'), ('licenciement', 'Licenciement'), ('mise_a_disposition', 'Mise à disposition'), ('mise_en_disponibilite', 'Mise en disponibilité'), ('mutation', 'Mutation'), ('position_militaire', 'Position militaire'), ('stagiaire', 'Stagiaire'), ('suspension_provisoire', 'Suspension provisoire')], default='en_activite', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('civil_servant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='JobDetail', to='core.civilservant')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('indemnities', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('tsp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('family_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('annual_gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cmr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sm', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ccd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('income_reduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taxable_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('income_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('civil_servant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='SalaryDetail', to='core.civilservant')),
            ],
        ),
        migrations.CreateModel(
            name='EchelonIndice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('echelon', models.PositiveSmallIntegerField()),
                ('indice', models.PositiveSmallIntegerField()),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echelons', to='core.grade')),
            ],
            options={
                'ordering': ['grade', 'echelon'],
                'unique_together': {('grade', 'echelon')},
            },
        ),
    ]
