# Generated by Django 6.1 on 2026-08-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetail',
            name='echelle',
            field=models.CharField(help_text='Associated with grade, e.g. tech 4th grade = échelle 9', max_length=10),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='echelon',
            field=models.PositiveSmallIntegerField(help_text="1–11, includes 'exceptionnelle'"),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='indice',
            field=models.PositiveSmallIntegerField(help_text="Échelon's salary-calc representation"),
        ),
    ]
