# Generated by Django 5.2.15 on 2026-07-01 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('zone_indemnity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tsp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('family_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('annual_gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cmr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sm', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ccd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('income_reduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taxable_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('income_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('civil_servant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_details', to='core.civilservant')),
            ],
        ),
    ]
