# Generated by Django 6.1 on 2026-08-23 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('label', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='categorie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='echelle',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='echelon',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='grade',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='indice',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.categorie')),
            ],
            options={
                'unique_together': {('categorie', 'code')},
            },
        ),
        migrations.CreateModel(
            name='EchelonIndice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('echelon', models.PositiveSmallIntegerField()),
                ('indice', models.PositiveIntegerField()),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echelons', to='core.grade')),
            ],
            options={
                'ordering': ['grade', 'echelon'],
                'unique_together': {('grade', 'echelon')},
            },
        ),
    ]
