# Generated by Django 6.1 on 2026-08-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_categorie_grade_indice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echelonindice',
            name='indice',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='echelle',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='echelon',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
